#!/usr/bin/perl

use 5.014;
use warnings;
use File::Basename;
use Cwd qw(abs_path);

my $subcmd = $ARGV[0];
$subcmd = 'help' if !defined $subcmd;

my $dirname = dirname(abs_path($0));
my $subcmdpath = abs_path("$dirname/acne-$subcmd");

exec($subcmdpath, @ARGV)
 or die "Can't exec $subcmdpath: $!\n";